id: A99D2B9D1
title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
type: translation
pechas:
- I5E3C443E
- IC7E884DE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:42:59.544844
  last_modified_at: 2023-01-04 11:42:59.544855
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I5E3C443E/9350: AC55
  IC7E884DE/9E58: AC55
